config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  root to: 'products#home'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  scope :last_three, -> { order(created_at: :desc).limit(3) }
  scope :usa, -> { where(country_of_origin: "USA") }
  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost, products.country_of_origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}
    
    def self.search(search)
      if search
        where(["name ILIKE ?","%#{search}%"])
      else
        all
      end
    end  

  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true

  before_save(:titleize_product)

  private
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content, presence: true
  validates :rating, presence: true
  validates_length_of :content, within: 50..250

  before_save(:titleize_review)

  private
    def titleize_review
      self.author = self.author.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :is_admin?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page. Please Sign In."
      redirect_to '/'
    end
  end

  def is_admin?
    current_user && current_user.admin
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize, except: [:home]
  
  def home
    if params[:sort] == "usa"
      @products = Product.usa
    elsif params[:sort] == "most_reviews"
      @products = Product.most_reviews
    else params[:sort] == "recent"
      @products = Product.last_three
    end 
    render :home
  end

  def index
    @products = Product.search(params[:search]).paginate(:page => params[:page], per_page:10)
    render :index
  end

  def new
    if is_admin?
      @product = Product.new
      render :new
    else
      flash[:alert] = "You aren't authorized to visit that page. Must be an Admin."
      redirect_to '/'
    end    
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      render :new
    end
  end

    def edit
      if is_admin?
        @product = Product.find(params[:id])
        render :edit
      else
        flash[:alert] = "You aren't authorized to visit that page. Must be an Admin."
        redirect_to '/'
      end   
    end

    def show
      @product = Product.find(params[:id])
      render :show
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(product_params)
        flash[:notice] = "Product successfully updated!"
        redirect_to products_path
      else
        render :edit
      end
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      flash[:notice] = "Product successfully DESTROYED!!"
      redirect_to products_path
    end

    private
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    if is_admin?
      @product = Product.find(params[:product_id])
      @review = Review.find(params[:id])
      render :edit
    else
      flash[:alert] = "You aren't authorized to visit that page. Must be an Admin."
        redirect_to '/'
    end
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_path(@review.product)
    else
      @product = Product.find(params[:product_id])
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review successfully DESTROYED!!"
    redirect_to product_path(@review.product)
  end

  private
    def review_params
      params.require(:review).permit(:author, :content, :rating)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <div class="field form-group">
    <%= f.text_field :name, class:'form-control', placeholder: "Name" %>
  </div>
<br>  
  <div class="field form-group">
    <%= f.number_field :cost, class:'form-control', placeholder: "Cost" %>
  </div>
<br>  
  <div class="field form-group">
    <%= f.text_field :country_of_origin, class:'form-control', placeholder: "Country of Origin" %>
  </div>
<br>
  <div class="actions">
    <%= f.submit class:'btn btn-warning' %>
  </div>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <div class="field form-group">
    <%= f.text_field :author, class:'form-control', placeholder: "Author" %>
  </div>
<br> 
  <div class="field form-group">
    <%= f.text_area :content, class:'form-control', placeholder: "Content" %>
  </div>
<br>
  <div class="field form-group">
    <%= f.label :rating %>
    <%= f.select :rating, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5]] %>
  </div>
<br>
  <div class="actions">
    <%= f.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title>ZarasMusicalEquipment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="container">
    <%= link_to "Home", '/' %>

    <% if current_user %>
        <%= "Welcome, #{current_user.email.capitalize}" %> | <%= link_to "Sign out", '/signout' %>
    <% else %>
        <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
    <% end %>

    <%= form_tag products_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], placeholder: "Find Products" %>
        <%= submit_tag "Search" %>
    <% end %>

    <header class="container">
      <h1>Zara's Musical Equipment</h1>
    </header>
    
    <div class="notice alert-warning" role="alert">
      <%= alert %>
    </div>
    <div class="notice alert-primary"> 
      <%= notice %>
    </div>  

    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<div class="jumbotron">
  <h2>Edit Product</h2>
  <%= render "layouts/product_form" %>
</div>

app/views/products/home.html.erb
<div class='jumbotron'>
  <h6>ZarasMusicalEquipment ,or ZME, is a family owned business that has been passed down for centuries. </h6>
  <h6>Many years ago when Zara was just a wee lass, she lived on the magical island of Ireland. One day she was walking along through a quite forest and heard a percussive rhythm coming from a distance. As she aproached she saw woodland creature rocking out on a sick 7 piece drumset. Just as she was opening her mouth to talk to the creature, two birds flew overhead carrying an electric flying-V guitar. The birds placed the strap over her shoulder and the intrument fell into her hands. It fit better than Cinderella's slipper. There no doubt in her mind, she knew it was time to ROCK!! She and her woodland drummer and all of the birds and the trees jammed. In fact, they jammed and rocked and harmonized and synchronized and solo'd until every string on her guitar was was forced to surrender and snap.</h6>
  <h6>It was at that moment she knew...she knew that she wanted to open up an e-commerce business that sold the best musical equipment at competitive prices and offer free shipping on all orders over $250.</h6>
</div>
<div class="wrapper">
  <a href="?sort=recent"><button class="btn btn-secondary">Recently added</button></a>
  <a href="?sort=most_reviews"><button class="btn btn-secondary">Most Reviews</button></a>
  <a href="?sort=usa"><button class="btn btn-secondary">Made in USA</button></a>
  <%= link_to "All Products", products_path, class:"btn btn-dark" %>
</div>

<table class='table table-striped table-bordered table-hover'>
  <thead class='thead-dark'>
    <tr>
      <th>Products</th> 
    </tr>
  </thead>
  
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/index.html.erb
<div class="jumbotron">
  <table class='table table-striped table-bordered table-hover'>
    <thead class='thead-dark'>
      <tr>
        <th>Here is our full list of Products</th>  
      </tr>
    </thead>
    <tbody>
    <% if @products.any? %>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.name, product_path(product) %></td>
        </tr>
      <% end %>
      <% else %>
        <p>There are currently no products.</p>
      <% end %>
    </tbody>
  </table>
</div>
<div class='row'>
  <div class='col-sm'>
    <%= will_paginate @post,renderer: BootstrapPagination::Rails %>
  </div>
  <div class='col-sm-3'>
    <% if is_admin? %>
      <%= link_to "Create new product", new_product_path, class: 'btn btn-warning' %>
    <% end %>  
  </div>
</div>

app/views/products/new.html.erb
<div class="jumbotron">
  <h2>New Product</h2>
  <%= render "layouts/product_form" %>
</div>

app/views/products/show.html.erb
<div class='jumbotron'>
  <h2><%= @product.name %></h2>
  <h3>Price:  $<%= @product.cost %></h3>
  <h4>Made in: <%= @product.country_of_origin %></h4>

  <% if @product.reviews.any? %>
    <h4>Here are the reviews for this product:</h4>
    <% @product.reviews.each do |review| %>
      <ul>
        <li>
          <p>from customer: <%= link_to review.author, product_review_path(@product, review) %></p>
        </li>
      </ul>
    <% end %>
  <% else %>
    <p>No reviews are listed for this product.</p>
  <% end %>

  <p><%= link_to "Add a review", new_product_review_path(@product), class: 'btn btn-warning' %></p>
  <% if is_admin? %>
    <%= link_to "Edit", edit_product_path(@product), class:"btn btn-secondary" %>
    <%= link_to "Delete", product_path(@product), class:"btn btn-secondary",
                            :data => {:confirm => "You sure?",
                                      :method => "delete"} %>
  <% end %>                                    
  <%= link_to "Return to products", products_path, class:"btn btn-dark" %>
</div>

app/views/reviews/edit.html.erb
<div class="jumbotron">
  <h2>Edit Review</h2>
  <%= render "layouts/review_form" %>
</div>

app/views/reviews/new.html.erb
<div class="jumbotron">
  <h2>Write a Review</h2>
  <%= render "layouts/review_form" %>
</div>

app/views/reviews/show.html.erb
<div class="jumbotron">
  <h2>Reviewer: <%= @review.author %></h2>
  <h3>Product: <%= @product.name %></h3>
  <h4>Rating: <%= @review.rating %></h4>
  <h4><%= @review.content %></h4>

  <% if is_admin? %>
    <%= link_to "Edit review", edit_product_review_path(@product, @review), class:"btn btn-secondary" %>
    <%= link_to "Delete review", product_review_path(@product, @review), class:"btn btn-secondary",                 
                            :data => {:confirm => "Are you sure?",
                                          :method => "delete"} %>
  <% end %>                                      
  <%= link_to "Return to product", product_path(@product), class:"btn btn-dark" %>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
  <h2> Sign up</h2>
  <%= form_for @user do |f| %>
    <%= f.label "Email" %>
    <%= f.text_field :email, class:'form-control', placeholder:'Email' %>
      <br>
    <%= f.label "Password" %>
    <%= f.password_field :password, class:'form-control', placeholder:'Password' %>
      <br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:'form-control', placeholder:'Confirm Password' %>
      <br>
    <%= f.label :admin %>
    <%= f.select :admin, [["False", false], ["True", true]] %>
      <br>
    <%= f.submit "Sign Up", class:'btn btn-warning' %>
  <% end %>
</div>